name: Backend Tests

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: macos-latest # Ändrad inställning för macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend and Install Dependencies
        run: |
          cd Backend
          npm install
          npm test
        shell: bash

      - name: Upload Code Coverage to GitHub
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          path: Backend/coverage
