name: Backend Tests

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.3

      - name: Set up Node.js for Backend and Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies and Run Tests
        run: |
          cd Backend
          npm install
          npm test
        shell: bash

      - name: Upload Code Coverage to GitHub
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          path: Backend/coverage
