name: Frontend Tests

on:
  push:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: macos-latest # Ändrad inställning för macOS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: Frontend

      - name: Run Frontend Tests with Code Coverage
        run: |
          npm run cypress:run:coverage
        working-directory: Frontend

      - name: Upload Code Coverage to GitHub
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: frontend-coverage
          path: Frontend/coverage
