name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Backend Dependencies, build, and start
        run: |
          cd backend
          npm install
          npm run build
          npm start
        working-directory: backend

      - name: Install Frontend Dependencies, build, and start
        run: |
          cd frontend
          npm install
          npm run build
          npm start
        working-directory: frontend

      - name: Run Cypress Tests
        run: npx cypress open
