name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Set Proxy
        run: |
          export HTTP_PROXY=http://127.0.0.1
          export HTTPS_PROXY=http://127.0.0.1
          export NO_PROXY=localhost,127.0.0.1,127.0.0.1:5173

      - name: Install Dependencies
        run: |
          npm install
          cd frontend && npm install
          cd ../backend && npm install

      - name: Start Backend and Frontend
        run: |
          cd backend && npm run dev &
          cd ../frontend && npm run dev &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm run dev
