name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Frontend Dependencies
        run: npm install

      - name: Start Frontend
        run: npm run dev &

      - name: Wait for Frontend to Start
        run: sleep 30

      - name: Cypress run for Frontend
        uses: cypress-io/github-action@v6

  cypress-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Backend Dependencies
        run: npm install

      - name: Start Backend
        run: npm run dev &

      - name: Wait for Backend to Start
        run: sleep 30

      - name: Run Backend Tests
        run: npm test
