name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Start Backend
        run: cd backend && npm run dev

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Start Frontend
        run: cd frontend && npm run dev

      - name: Wait for Backend and Frontend to Start
        run: |
          wait-on http://localhost:5173
          wait-on http://localhost:3002

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
