name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install

      - name: Build and Start Backend
        run: |
          cd backend
          npm run build
          npm run start &

      - name: Wait for Backend to Start
        run: wait-on http://localhost:3002

      - name: Build Frontend
        run: |
          cd ../frontend
          npm run build

      - name: Start Frontend
        run: npm run start &

      - name: Wait for Frontend to Start
        run: wait-on http://localhost:5173

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm run start
