name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    needs: backend-frontend-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev

  backend-frontend-setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Start Backend
        run: |
          cd backend
          npm run dev &

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Start Frontend
        run: |
          cd frontend
          npm run dev &

      - name: Wait for Backend to Start
        run: sleep 30

      - name: Wait for Frontend to Start
        run: sleep 10
