name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Current Directory
        run: |
          pwd

      - name: Install Backend Dependencies, build, and start
        run: |
          cd fullstack-ish-typescript/backend
          npm install
          npm run build
          npm start
        working-directory: fullstack-typescript-Labb3/backend

      - name: Install Frontend Dependencies, build, and start
        run: |
          cd fullstack-ish-typescript/frontend
          npm install
          npm run build
          npm start
        working-directory: fullstack-typescript-Labb3/frontend

      - name: Run Cypress Tests
        run: |
          cd fullstack-ish-typescript/frontend
          npx cypress open
