name: Cypress Run

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            backend/node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          npm install
          cd frontend && npm install
          cd ../backend && npm install

      - name: Start Backend (in the background)
        run: cd backend && npm run dev &

      - name: Wait for Backend to Start
        run: sleep 5

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          wait-on: "http://localhost:5173"
          start: npm run dev
          config-file: cypress.config.ts
