name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install NPM dependencies and run backend
      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
          npm run dev

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests for frontend
      - name: Cypress run for frontend
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          build: npm run build
          start: npm run dev
