name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Current Directory
        run: |
          pwd

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: |
          npm install
          npm run build
          npm run dev

      - name: Run Cypress Tests
        working-directory: frontend
        run: |
          npx cypress open
