name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install wait-on
        run: npm install wait-on

      - name: Install Dependencies
        run: |
          npm install
          cd frontend && npm install
          cd ../backend && npm install

      - name: Start Backend and Frontend
        run: |
          cd backend && npm run dev &
          cd ../frontend && npm run dev &

      - name: Wait for Backend and Frontend to Start
        run: npx wait-on http://localhost:3002 http://localhost:5173

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm run dev
