name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Start Backend
        run: cd backend && npm run dev &

      - name: Wait for Backend to Start
        run: sleep 20

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Start Frontend
        run: cd frontend && npm run dev &

      - name: Wait for Frontend to Start
        run: sleep 20

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm run dev
