name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Start Backend
        run: |
          cd backend
          npm run dev &
          sleep 5 # Wait for backend to start

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Start Frontend
        run: |
          cd frontend
          npm run dev &
          sleep 5 # Wait for frontend to start

      - name: Wait for Backend and Frontend to Start
        run: wait-on http://localhost:3002 http://localhost:5173

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          build: npm run build
          start: npm run dev
