name: Cypress Tests on Push

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: |
          npm install
          cd frontend && npm install
          cd ../backend && npm install

      - name: Start Backend (in the background)
        run: cd backend && npm run dev &

      - name: Wait for Backend to Start
        run: sleep 5

      - name: Start Frontend
        run: cd frontend && npm run dev
